### ISSUE TITLE
[M3: R]

### ISSUE THREAD

**Issue by slumnitz** [UBC-MDS/flight-explorer-R#9]
Hello everyone,

great work updating your proposal, progress report and ,erging each others PR's!

Here are a couple of comments:
* you need to improve your commit messages to receive full marks next time. Instead of writing `Update README.md` be more specific and i.e. write `add R-progress to README.md`
* since you chose 2 relatively simple visualisations for your analysis, which is great because you can focus on practicing interactivity, I would recommend you to focus on trying to include as much interactivity as possible and provide a visually pleasing R app for M4. I would expect a fairly polished app by the end of your submission.

Feel free to tag me in any issues or comments in case you need a pointer what to focus on or have questions.

**Comment by v5y8** [comment]
we've addressed this in [reflections.md](https://github.com/UBC-MDS/flight-explorer-R/blob/master/reflection.md)
